export const AES_SECRET = process.env.AES_SECRET || ''
export const AD_CLIENT_ID = process.env.AD_CLIENT_ID || ''
export const AD_CLIENT_SECRET = process.env.AD_CLIENT_SECRET || ''
export const AD_API_BASE_URL = process.env.NEXT_PUBLIC_AD_API_URL || ''
export const ROLE_API_URL = process.env.NEXT_PUBLIC_ROLE_API_URL || ''
export const AD_AUTH_API_URL = process.env.NEXT_PUBLIC_AD_AUTH_API_URL || ''
export const AD_AUTH_CLIENT_ID = process.env.AD_AUTH_CLIENT_ID || ''
export const AD_AUTH_SERVICE_ID = process.env.AD_AUTH_SERVICE_ID || ''
